/********************************************************************************************/
/*  Name            Date                                Description                          */
/*  Developer2      11-10-2022                          Included Sub class in calculator     */
/*********************************************************************************************/


public with sharing class calculator {
    public calculator() {

    }
}



