/***************************************************************************/
/* Name             Date                                Decription*        */
/*Developer1        22-10-2022                  Added Add Method to Class  */
/***************************************************************************/

public with sharing class calculator {
    //base method calculator will call other methods like add, substract, multiply,etc.
    public calculator() {

    }
    public integer add(integeer a, integer b){
        return a+b;
    }
}



