
/***************************************************************************/
/* Name             Date                                Decription*        */
/*Developer1        22-10-2022                  Added Add Method to Class  */
/***************************************************************************
public with sharing class calculator() {
    public calculator(){
    }  
    public integer add(integeer a, integer b){
        return a+b;
    }
}



